# -*- coding: utf-8 -*-
"""Round 12：󺡅 的原拓核验"""
import io, os, sys, json
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "甲骨文未释字_原拓核验_gx21ndp7yy.md")

L = []
L.append("# 未释字 󺡅 的原拓核验\n")
L.append("编制：2026-10-03\n")
L.append("> 本会话前十一轮的字形判断**全部基于摹本**（OBIMD 的 subchar_images）。")
L.append("> 本文首次取到**原拓**并目验，这是考释工作的必要起点。\n")
L.append("---\n")

L.append("## 一、拓片来源\n")
L.append("《甲骨文合集》图版可由公开释文库直接取得，URL 形如：\n")
L.append("```")
L.append("https://pic2.39017.com/jgwhj/<册号>/00<片号>.png")
L.append("例如  https://pic2.39017.com/jgwhj/1/005250.png")
L.append("```")
L.append("本文取到 󺡅 相关的 7 片：5250、5252、5253、5254、5259、5305、5326。\n")

L.append("## 二、核验结果（《合集》5250）\n")
L.append("该片释文（事何類（賓））：")
L.append("```")
L.append("鼎（貞）：王□叀（惠）吉，不冓（遘）雨。")
L.append("〔鼎（貞）〕：王□〔叀（惠）吉〕，□冓（遘）〔雨〕。")
L.append("```")
L.append("**原拓目验**：右下区域可辨出三行文字，其中第二字（即释文中的「□」＝󺡅）")
L.append("的形体为：\n")
L.append("| 部位 | 拓片所见 | 与摹本是否一致 |")
L.append("|---|---|---|")
L.append("| 顶部 | **交叉形（枝杈状）** | ✅ 一致 |")
L.append("| 中部 | **三角形／帳篷形轮廓，内有笔画** | ✅ 一致（摹本作方框／椭圆，为拓本磨损后的规整化） |")
L.append("| 下部 | **两笔分叉（腿形）** | ✅ 一致 |")
L.append("")
L.append("**结论：原拓与 OBIMD 摹本的结构一致。**")
L.append("摹本对该字中部的处理比原拓更规整（摹本作方圆框，原拓为三角／帳篷形），")
L.append("这是摹本通例（摹写者对磨损处作规整化），不影响构形判定。\n")

L.append("## 三、构形的最终描述（综合摹本 4 形与原拓）\n")
L.append("```")
L.append("        ╱╲            ← 顶部：交叉／枝杈形")
L.append("       ╱  ╲")
L.append("      ╱____╲          ← 中部：三角／帳篷形轮廓")
L.append("      │ ╳  │          ←       内有交叉笔画")
L.append("      │    │")
L.append("      ╱╲  ╱╲          ← 下部：两笔分叉")
L.append("```")
L.append("**判定性特征：顶部交叉 ＋ 中部三角形轮廓（内有笔画）＋ 下部叉形。**\n")

L.append("## 四、与相关字的最终对照\n")
L.append("| 字 | 顶部 | 中部 | 下部 | 与 󺡅 |")
L.append("|---|---|---|---|---|")
L.append("| 󺡅 | 交叉 | 三角／帳篷形，内有笔画 | 叉形 | — |")
L.append("| 木 | 上扬枝 | 无 | 叉形 | 下部同，其余不同 |")
L.append("| 余 | 尖顶 | 方框 | 叉形 | **结构层次相同**，中部不同 |")
L.append("| 舍 | 尖顶 | 方框／口 | 叉形 | **结构层次相同** |")
L.append("| 宋 | 宀 | 木 | 叉形 | 顶部为宀，不同 |")
L.append("| 宗 | 宀 | 示 | 叉形 | 顶部为宀，不同 |")
L.append("| 舎 | 尖顶 | 口 | 叉形 | 结构近 |")
L.append("| 京 | 尖顶 | 方框 | 丨 | 下部不同 |")
L.append("| 高 | 尖顶 | 方框 | 口 | 下部不同 |")
L.append("| 亳 | 尖顶 | 方框 | 乇 | 下部不同 |")
L.append("")
L.append("**值得注意的是：「余」「舍」「舎」与 󺡅 有相同的三段式层次结构**")
L.append("（尖顶／交叉顶 ＋ 中部框 ＋ 下部叉形）。")
L.append("这类字形在甲骨文中是一组（旧多以「亼＋口＋乂」的构形相类），")
L.append("彼此区别处正在**中部的具体构形**。\n")

L.append("## 五、辞例与语法位置（复核）\n")
L.append("| 项 | 值 |")
L.append("|---|---|")
L.append("| 出现次数 | 54 |")
L.append("| 类组 | **事何類专有**（廪辛—康丁） |")
L.append("| 前邻 | 王（16 次） |")
L.append("| 后邻 | 叀（22 次） |")
L.append("| 核心套语 | **「貞 王 󺡅 叀（惠）吉」**（22 例） |")
L.append("| 《合集》能否隶定 | **不能**（私用区 U+E123／U+E124 占位） |")
L.append("")
L.append("## 六、结论\n")
L.append("1. **原拓核验通过**：拓片所见与摹本结构一致，且拓片更清晰（三角／帳篷形中部）。")
L.append("2. **构形最终判定**：顶部交叉 ＋ 中部三角／帳篷形（内有笔画）＋ 下部叉形。")
L.append("3. **与「余」「舍」「舎」层次结构相同**，区别在中部构形。")
L.append("4. **仍无读法。** 「余」「舍」为**假说**，未能通过辞例或音韵检验：")
L.append("   - 辞例：「王 󺡅 惠吉」为动词位，而「余」在卜辞中主要是第一人称代词，");
L.append("     置于「王」后作「王余…」不合语法。")
L.append("   - 若读「舍」（捨），则「王捨惠吉」文义亦不通。")
L.append("   故本文**不主张任何读法**。")
L.append("5. 本字的考释仍需：事何類專門字形表、甲骨文部件分解数据、专家目验。\n")

L.append("![原拓放大《合集》5250](figures/rub_005250_zoom.png)")
L.append("")
L.append("![摹本对照](figures/figQ_zoom.png)")
L.append("")
L.append("## 附：脚本与数据\n")
L.append("- `get_rubbing.py`　拓片下载（含 URL 格式）")
L.append("- `zoom_rub.py`　拓片文字区放大")
L.append("- `data/rubbings/`　7 片拓片")
L.append("- `figures/rub_005250_zoom.png`　原拓放大图")
L.append("")

open(OUT, "w", encoding="utf-8").write("\n".join(L))
print(f"[写出] {OUT}")
print(f"行数 {len(L)}")
