# -*- coding: utf-8 -*-
"""Round 5 报告：确认的事实 + 方法学教训"""
import io, os, sys, json, collections
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "result")
OUT = os.path.join(HERE, "甲骨文未释字_对齐方法评估.md")

r1 = json.load(open(os.path.join(RES, "align_records.json"), encoding="utf-8"))
r2 = json.load(open(os.path.join(RES, "align_v2.json"), encoding="utf-8"))
st1 = collections.Counter(x["status"] for x in r1)
st2 = collections.Counter(x["status"] for x in r2)

L = []
L.append("# OBIMD「未释字」与《合集》释文的自动对齐：方法评估\n")
L.append("编制：2026-10-03\n")
L.append("> 本报告记录三种自动对齐判据的实测结果，**其中两种被证伪**。")
L.append("> 保留的是已确认的事实与可复用工具，以及一条重要的方法学教训。\n")
L.append("---\n")

L.append("## 一、已确认的事实\n")
L.append("### 1.1 片号桥接（可靠）\n")
L.append("**OBIMD 片号 `H<n>` 与《甲骨文合集》编号 `n` 一一对应。**")
L.append("随机验证 5 片，释文内容逐条吻合。这使 OBIMD 与《合集》的释文可逐片对照。\n")
L.append("### 1.2 类组数据可得（可靠）\n")
L.append("《合集》释文库（国学大师）每条记录自带类组标注，可按片号、按字、按类组检索。")
L.append("实测「屯」返回 190 条，类组分布：典賓 88、典賓B 25、典賓A 20、賓出 12、賓三 6、")
L.append("師歷間 5、無名組 4、師賓間A 3、黃類 3。**此前认为缺失的类组数据，实为公开可得。**\n")
L.append("### 1.3 确证的编码缺失实例（逐条目验）\n")
L.append("| OBIMD 字形 | 片 |《合集》释文 | 对应字 |")
L.append("|---|---|---|---|")
L.append("| 󳪫 | 95 | 貞：率以罝芻 | **率** |")
L.append("| 󳩐 | 30319 | 其𠦪（禱）※，又大雨 | **𠦪**（禱之异体） |")
L.append("| 󹃑 | 313 | 翼乙亥㞢歲于唐 | 合文「**㞢歲**」 |")
L.append("| mepmffeebh | 575 | 翼戊戌于黃奭 | 合文「**于黃**」 |")
L.append("| 󳏬 | 30632 | 癸丑卜，何鼎（貞）：㞢至于… | **㞢** |")
L.append("")
L.append("这些在 OBIMD 中标为「无隶定」（即未释字），而《合集》释文已给出读法。")
L.append("原因可归三类：**合文**、**扩展区汉字未编码**、**罕用异体未收录**。\n")

L.append("## 二、三种自动对齐判据的实测结果\n")
L.append("| 判据 | 结果 | 评价 |")
L.append("|---|---|---|")
L.append(f"| 全局 Levenshtein 对齐 | 解出 {st1.get('合集解出',0)}／占位 {st1.get('合集亦占位',0)}／未对齐 {st1.get('未对齐',0)} | **不可靠**：长释文中配错位，产生假阳性 |")
L.append(f"| 多重集（字符计数）校验 | 解出 {st2.get('合集解出',0)}／证据不足 {st2.get('证据不足',0)} | **不可靠**：OBIMD 辞例是《合集》释文的子串，计数天然不匹配 |")
L.append("| 逐条目验 | 确认 5 例（见 1.3） | **可靠但不可规模化** |")
L.append("")
L.append("### 假阳性的证据\n")
L.append("Levenshtein 对齐把 󳏬 判为「《合集》亦占位」，但逐条目验《合集》30632 明确作：")
L.append("「癸丑卜，何鼎（貞）：**㞢**至于…」——即《合集》读作「㞢」。")
L.append("该条属对齐错误，非未释字。**这说明自动对齐的「占位」判定不可采信。**\n")

L.append("## 三、方法学教训\n")
L.append("1. **不可跳过目验**。三种自动判据中有两种给出与事实相反的结果。")
L.append("   甲骨辞例残断、多辞共版、释文体例不一（今字标注、合文、缺文符号混杂），")
L.append("   使自动对齐的误配率很高。")
L.append("2. **子串关系使计数类判据失效**。OBIMD 只收录部分辞例，且切分粒度与《合集》不同，")
L.append("   任何基于字符计数的校验都会失败。")
L.append("3. **可靠的做法只有逐片人工核对**，配合桥接表定位片号。这可以半自动化：")
L.append("   程序负责取片、拼释文、并排显示，人负责判定。\n")

L.append("## 四、当前可复用的产出\n")
L.append("| 工具／数据 | 说明 |")
L.append("|---|---|")
L.append("| `gxds2.py` | 《合集》释文＋类组抓取器，带缓存，支持按片号/按字/按类组检索 |")
L.append("| `bridge2.py` / `align.py` | 片号桥接与并排展示 |")
L.append("| `result/align_records.json` | 321 条逐片对照（含类组），供人工核对 |")
L.append("| `result/align_v2.json` | 多重集校验结果（已证伪，保留备查） |")
L.append("| `data/gxds2/` | 629 页释文缓存（含类组） |")
L.append("")
L.append("## 五、对目标的评估\n")
L.append("本会话仍未考释出任何一个甲骨文未释字。本轮新增的确认事实是：")
L.append("**OBIMD 语料中的一部分「未释字」实为该数据集的编码缺失**（5 例已逐条确认），")
L.append("**且类组数据公开可得**。但要把「一部分」变成准确的数量与清单，")
L.append("需要逐片人工核对 321 条对照记录——这超出自动方法的可靠范围。\n")

open(OUT, "w", encoding="utf-8").write("\n".join(L))
print(f"[写出] {OUT}")
print(f"已确认编码缺失实例 5 例；两种自动判据被证伪")
