# -*- coding: utf-8 -*-
"""
Round 7 记录：󷺊（40 次）的完整分析
结论：彡 假设被证伪；该字为晚期黄组字，但无判定性证据
"""
import io, os, sys, json, collections
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "甲骨文未释字_字形分析_ff8rp0nh6u.md")
OB = os.path.join(HERE, "data", "obimd")
mc = json.load(open(os.path.join(OB, "main_character.json"), encoding="utf-8"))
data = json.load(open(os.path.join(OB, "data.json"), encoding="utf-8"))
cp = lambda l: mc.get(l, {}).get("codepoint") or ""

sh = json.load(open(os.path.join(HERE, "result", "shān_hypothesis.json"), encoding="utf-8"))

L = []
L.append("# 未释字 󷺊（ff8rp0nh6u）的辞例结构与字形分析\n")
L.append("编制：2026-10-03\n")
L.append("> 本文报告对一个具体未释字的系统分析。**假设被证伪，结论为「无判定性证据」。**")
L.append("> 记录于此，供后续研究参考，并作为「不可轻下结论」的实例。\n")
L.append("---\n")

L.append("## 一、对象\n")
L.append("| 项 | 值 |")
L.append("|---|---|")
L.append("| OBIMD 字形码位 | 󷺊 |")
L.append("| OBIMD 内部编号 | `ff8rp0nh6u` |")
L.append("| 出现次数 | 40 |")
L.append("| 字形数 | 4 |")
L.append("| 隶定 | 无（OBIMD 标为未释） |")
L.append("")

L.append("## 二、类组分布（决定性线索）\n")
L.append("按《甲骨文合集》释文的类组标注统计：\n")
L.append("| 类组 | 条数 |")
L.append("|---|---|")
L.append("| 黃 | 35 |")
L.append("| 出二 | 3 |")
L.append("| 賓出 | 1 |")
L.append("| 其他 | 1 |")
L.append("")
L.append("**40 次中 35 次属黃组**（帝乙—帝辛时期）。这是本字最显著的特征：")
L.append("它是一个**晚期黄组字**。黄组卜辞以周祭（五祀典）与旬亡祸卜辞为主。\n")

L.append("## 三、辞例结构\n")
L.append("全部 40 条辞例中，该字出现的句式可归为两类：\n")
L.append("### 3.1　「王賓 X 󷺊 亡尤／亡祸」\n")
L.append("```")
L.append("H22698  丙申卜旅貞   王 賓 󾷎   󷺊   亡 祸")
L.append("H35451  丙申卜貞     王 賓 󾷎   󷺊   亡 尤")
L.append("H35459  丁巳卜貞     王 賓 󾷝   󷺊   亡 尤")
L.append("H35615  己巳卜貞     王 賓 󿎀   󷺊   亡 尤")
L.append("H35866  己巳卜貞     王 賓 󿈌   󷺊   亡 尤")
L.append("```")
L.append("### 3.2　周祭旬亡祸卜辞中，位于日名与祭名之间\n")
L.append("```")
L.append("H35530  癸卯王卜貞 旬亡򶫴 … 甲辰 󷺊 󾸳 祭 小甲")
L.append("H35576  癸卯王卜貞 旬亡򶫴 在四夕 甲辰 󷺊 󾻭 協 󾸳")
L.append("H35748  癸巳王卜貞 旬亡򶫴 甲正夕 … 甲午 󷺊 򧇂 甲 協 羌甲")
L.append("H35749  癸丑卜򮚺貞 旬亡򶫴 甲三夕 甲寅 祭 󿁪 甲 󷺊 羌甲 協 󿀹 甲")
L.append("```")
L.append("### 3.3　后邻字统计\n")
L.append("| 后邻字 | 次数 |")
L.append("|---|---|")
for k, v in list(sh["after"].items())[:10]:
    L.append(f"| {k} | {v} |")
L.append("")
L.append(f"- 后邻为**天干／地支字**者：**{sh['ganzhi_after']}/40 = {sh['ganzhi_after']/40:.0%}**")
L.append(f"- 后邻为**祭名字**者：**{sh['ritual_after']}/40 = {sh['ritual_after']/40:.0%}**")
L.append(f"- 同片辞例含「夕」者：{sh['with_xi']}/40 = {sh['with_xi']/40:.0%}")
L.append("")

L.append("## 四、被证伪的假设：󷺊 = 「彡」\n")
L.append("### 4.1　假设的由来\n")
L.append("周祭五祀典为「彡、翌、祭、劦、肜」，格式作「甲辰**彡**日祭小甲」。")
L.append("󷺊 大量出现于周祭旬亡祸卜辞、且位于日名之后，形式上与「彡」的位置相符。\n")
L.append("### 4.2　证伪证据\n")
L.append("1. **后邻字不符**：若为「彡」，后邻应为「日」或日名。实测后邻为日名者仅 1/40（2%），")
L.append("   为祭名者 0/40。")
L.append("2. **字形不符**：见字形对照（图 K）。「彡」的甲骨文作三斜画，極简；")
L.append("   而 󷺊 作「竖干＋中部圆／方＋横画交叉」，部分形体右侧另有「又」形，")
L.append("   是一个结构复杂的字，与「彡」无任何相似。")
L.append("3. **字表冲突**：「彡」在 OBIMD 语料中已有独立字形类（出现 120 次），")
L.append("   若 󷺊 即「彡」，则须证明二者为同字异写，而字形差异使此证明不可能。")
L.append("")
L.append("**结论：假设不成立。**\n")

L.append("## 五、字形描述\n")
L.append("据 4 个字形（图 K）目验：\n")
L.append("- 主体为**一竖干**，贯中")
L.append("- 中部为**圆形或方框**")
L.append("- 有**横画交叉**（部分形体作两条横画）")
L.append("- 部分形体右侧附**「又」（手）形**，另有小点状笔画")
L.append("")
L.append("这一结构与「東」（束橐之形）或「專」等字形有形式上的接近，")
L.append("但**均无辞例或音韵证据支持**，故不主张任何读法。\n")

L.append("## 六、结论与限度\n")
L.append("1. 󷺊 是一个**晚期黄组字**（40 次中 35 次属黄组），主要出现在")
L.append("   「王賓X亡尤」套语与周祭旬亡祸卜辞中。")
L.append("2. 「彡」的假设**已被辞例与字形双重证伪**。")
L.append("3. **本字仍无判定性读法。** 它与「亡」的高共现率（后邻 42%）是套语位置造成的，")
L.append("   不构成语义线索。")
L.append("4. 要推进此字，需要的是**黄组字形的系统对比**")
L.append("   （黄组字形有较强的时代特征），这需要黄组字形的专门字形表，")
L.append("   本会话不具备该资源。")
L.append("")
L.append("![字形对照](figures/figK_shan.png)")
L.append("")
L.append("## 附：数据\n")
L.append("- `result/shān_hypothesis.json`　辞例统计")
L.append("- `compare_shan.py`　与「彡」的对照脚本")
L.append("- `figures/figK_shan.png`　字形对照图")
L.append("")

open(OUT, "w", encoding="utf-8").write("\n".join(L))
print(f"[写出] {OUT}")
print(f"行数 {len(L)}")
